# 控制台与日志
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

# GPIO 与输入子系统 (BOOT 按键 GPIO9)
CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y

# I2C (板载传感器与触摸屏, 外部接口 J1)
CONFIG_I2C=y
